learning_log/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^learning_log/',include('learning_logs.urls',namespace='learning_logs')), 
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^reading/',include('reading.urls',namespace='reading')),
    url(r'^test/',include('mytest.urls',namespace='test')),
    url(r'^love/',include('lovestory.urls',namespace='love')),
    
]

learning_logs/urls.py
from django.conf.urls import url

from . import views

urlpatterns=[

	url(r'^$',views.index,name='index'),
	url(r'^topics/$',views.topics,name='topics'),
	url(r'^topic/(?P<topic_id>\d+)/$',views.topic,name='topic'),
	url(r'^new_topic/$',views.new_topic,name='new_topic'),
	url(r'^new_entry/(?P<topic_id>\d+)/$',views.new_entry,name='new_entry'),
	url(r'^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry,name='edit_entry'),

	url(r'^search/$',views.search,name='search'),

]

reading/urls.py
from django.conf.urls import url

from . import views

urlpatterns=[
	url(r'^$',views.index),
	url(r'^(?P<namelist_id>\d+)/$',views.index,name='index'),
	url(r'^test/$',views.test,name='test'),
	url(r'^next/(?P<namelist_id>\d+)/$',views.next,name='next'),
	url(r'^before/(?P<namelist_id>\d+)/$',views.before,name='before'),
	url(r'^catalog/$',views.catalog,name='catalog'),
	url(r'^test2/$',views.test2,name='test2'),
]	

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns=[
	url(r'^login/$',login,{'template_name':'users/login.html'},name='login'),
	url(r'^logout/$',views.logout_view,name='logout'),
	url(r'^register/$',views.register,name='register'),
]

reading/models.py
from django.db import models

class NameList(models.Model):
	name=models.CharField(max_length=200)
	content=models.TextField()

	def __str__(self):
		return self.name

reading/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,Http404
from django.core.urlresolvers import reverse
from markdown import markdown

from .models import NameList
from learning_logs.models import Topic,Entry


# file_path='E:\\zongqiqi\\biandaima\\mypython\\txtread\\'
# filename='index.txt'
# with open(file_path+filename) as file:
# 	lines=file.readlines()
	

def index(request,namelist_id=1):
	# path="E:\\zongqiqi\\biandaima\\mypython\\txtread\\第一章.txt"
	filepath="E:\\zongqiqi\\biandaima\\mypython\\txtread\\"
	a=NameList.objects.get(id=namelist_id)
	# with open(filepath+a.name+'.txt') as file:
	# 	text=file.read()
	namelist=[]
	for i in range(12):
		if int(namelist_id)-5+i <0:
			namelist=NameList.objects.all()[:12]
			break
		if int(namelist_id)-5+i >784:
			namelist=NameList.objects.all()[772:]
			break
		else:
			namelist.append(NameList.objects.get(id=str(int(namelist_id)-5+i)))
	context={'a':a,'namelist':namelist,'namelist_id':namelist_id}
	return render(request,'reading/index.html',context)

#just test don't care
def test(request):
	return render(request,'reading/test.html')

#上一页
def next(request,namelist_id):
	newnamelist_id=int(namelist_id)+1
	return HttpResponseRedirect(reverse('reading:index',args=[newnamelist_id]))
#上一页
def before(request,namelist_id):
	newnamelist_id=int(namelist_id)-1
	return HttpResponseRedirect(reverse('reading:index',args=[newnamelist_id]))

#还差一个目录
def catalog(request):
	alllist=NameList.objects.all()
	alllist_1=alllist[:200]
	alllist_2=alllist[200:400]
	alllist_3=alllist[400:600]
	alllist_4=alllist[600:]
	context={'alllist_1':alllist_1,'alllist_2':alllist_2,'alllist_3':alllist_3,'alllist_4':alllist_4,}
	return render(request,'reading/catalog.html',context)

def test2(request,topic_id=14):
	topic=Topic.objects.get(id=topic_id)
	if topic.owner!=request.user:
		raise Http404

	entries=topic.entry_set.order_by('-date_added')
	for entry in entries:
		entry.text=markdown(entry.text,extensions=['markdown.extensions.extra',
													'markdown.extensions.codehilite',
													'markdown.extensions.toc',])


	context={'topic':topic,'entries':entries}
	return render(request,'reading/test2.html',context)

reading/templates/reading/catalog.html
{% load bootstrap3 %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
            <title><div class="jumbotron">
                阳神——Catalog
            </div>></title>
            <meta name="keywords">
                <meta name="description">
                            {% bootstrap_css %}
      {% bootstrap_javascript %}
                    <style>
                        canvas{
  position:absolute;
  top:0;
  left:0;
  background-color:black;
}
div.box{
  background-color: white;
  width: 200px;
}
                    </style>
                </meta>
            </meta>
        </meta>
    </head>
    <body>
        <canvas height="599" id="c" style="position:fixed" width="1366">
        </canvas>
        <script src=" {%static 'reading/index.js' %}"></script>
                <div class="col-lg-11 modal-content" style="background-color: white; opacity:0.8;width:1300px;margin:10 auto">
                <h1 style="text-align:center">阳神</h1>
                    <h3 style="padding: 35px;text-align:center">
                    {% for entry in alllist_1 %}
                        <a style="float:left;background-color: white; opacity:0.8;margin:20px;" href="{% url 'reading:index' entry.id %}">{{entry.name}}</a>
                    {% endfor %}
                    {% for entry in alllist_2 %}
                        <a style="float:left;background-color: white; opacity:0.8;margin:20px" href="{% url 'reading:index' entry.id %}">{{entry.name}}</a>
                    {% endfor %}
                    {% for entry in alllist_3 %}
                        <a style="float:left;background-color: white; opacity:0.8;margin:20px" href="{% url 'reading:index' entry.id %}">{{entry.name}}</a>
                    {% endfor %}
                    {% for entry in alllist_4 %}
                        <a style="float:left;background-color: white; opacity:0.8;margin:20px" href="{% url 'reading:index' entry.id %}">{{entry.name}}</a>
                    {% endfor %}


                    </h3>
                    </div>
                    </div>


    </body>
</html>

reading/templates/reading/index.html
{% load bootstrap3 %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
            <title>
                额，瞎做了一个网页看小说的
            </title>
            <meta name="keywords">
                <meta name="description">
                    <style>
                        canvas{
  position:absolute;
  top:0;
  left:0;
  background-color:black;
}
div.box{
  background-color: white;
  width: 200px;
}
                    </style>
                </meta>
            </meta>
        </meta>
    </head>
    <body>
        <canvas height="599" id="c" style="position:fixed" width="1366">
        </canvas>
        <script src=" {%static 'reading/index.js' %}"></script>


                <div class="col-md-1 modal-content" style="background-color: white; opacity:0.8;width:100px;float:left;">
                      <h3><a href="{% url 'reading:catalog' %}">catalog</a></h3>
                    {% for name in namelist %}
                      <h4><a href="{% url 'reading:index' name.id %}">{{name.name}}</a></h4>
                    {% endfor %}

                </div>
                <div class="justtakespace" style="width:20px;float:left;" >111111</div>
                <div class="col-lg-11 modal-content" style="background-color: white; opacity:0.8;width:1000px;float:left;">
                    <h3 style="padding: 35px">
                        {{a.content|linebreaksbr}}
                    </h3>
                    <div class="btn-toolbar" role="toolbar">
                    <div class="btn-group" align="center">
                      <a class="btn btn-primary btn-large" href="{% url 'reading:before' namelist_id %}">上一页</a>
                      <a class="btn btn-primary btn-large" href="{% url 'reading:next' namelist_id %}">下一页</a>
                    </div>
                    </div>
                    </div>


    </body>
</html>

reading/templates/reading/test.html
{% load bootstrap3 %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
            <meta content="IE=ege" http-equiv="X-UA-Compatible">
                <meta content="width=device-width,initial-sacle=1" name="viewport">
                    <style>
                        canvas{
  position:absolute;
  top:0;
  left:0;
  background-color:black;
}
div.box{
  background-color: white;
  width: 200px;
}
                    </style>
                    <title>
                        Learning Log
                    </title>
                    {% bootstrap_css %}
				{% bootstrap_javascript %}
                </meta>
            </meta>
        </meta>
    </head>
    <body>
<!--         <canvas height="599" id="c" style="position:fixed" width="1366"></canvas>
        <script src=" {%static 'reading/index.js' %}"></script> -->

        <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <nav class="navbar navbar-default" role="navigation">
                        <div class="navbar-header">
                            <button class="navbar-toggle" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
                                <span class="sr-only">
                                    Toggle navigation
                                </span>
                                <span class="icon-bar">
                                </span>
                                <span class="icon-bar">
                                </span>
                                <span class="icon-bar">
                                </span>
                            </button>
                            <a class="navbar-brand" href="#">
                                Brand
                            </a>
                        </div>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li>
                                    <a href="#">
                                        Link
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Link
                                    </a>
                                </li>
                                <li class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                        Dropdown
                                        <strong class="caret">
                                        </strong>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="#">
                                                Action
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                Another action
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                Something else here
                                            </a>
                                        </li>
                                        <li class="divider">
                                        </li>
                                        <li>
                                            <a href="#">
                                                Separated link
                                            </a>
                                        </li>
                                        <li class="divider">
                                        </li>
                                        <li>
                                            <a href="#">
                                                One more separated link
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                            <form class="navbar-form navbar-left" role="search">
                                <div class="form-group">
                                    <input class="form-control" type="text"/>
                                </div>
                                <button class="btn btn-default" type="submit">
                                    Submit
                                </button>
                            </form>
                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                    <a href="#">
                                        Link
                                    </a>
                                </li>
                                <li class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                        Dropdown
                                        <strong class="caret">
                                        </strong>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="#">
                                                Action
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                Another action
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                Something else here
                                            </a>
                                        </li>
                                        <li class="divider">
                                        </li>
                                        <li>
                                            <a href="#">
                                                Separated link
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </nav>
                    <div class="jumbotron well" style="opacity: 0.7">
                        <h1>
                            Hello, world!
                        </h1>
                        <p>
                            This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.
                        </p>
                        <p>
                            <a class="btn btn-primary btn-large" href="#">
                                Learn more
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-md-4 column">
                    <h2>
                        Heading
                    </h2>
                    <p>
                        Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
                    </p>
                    <p>
                        <a class="btn" href="#">
                            View details »
                        </a>
                    </p>
                </div>
                <div class="col-md-4 column">
                    <h2>
                        Heading
                    </h2>
                    <p>
                        Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
                    </p>
                    <p>
                        <a class="btn" href="#">
                            View details »
                        </a>
                    </p>
                </div>
                <div class="col-md-4 column">
                    <h2>
                        Heading
                    </h2>
                    <p>
                        Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
                    </p>
                    <p>
                        <a class="btn" href="#">
                            View details »
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </body>
</html>

reading/templates/reading/test2.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}



{% block header %}
<h1>
    Topics
</h1>
{% endblock header %}

{% block content %}
<h2>
    This my test
</h2>
<div class="panel-group" id="panel-677207">
    <div class="panel panel-default">
        <div class="panel-heading">
            <a class="panel-title collapsed" data-parent="#panel-677207" data-toggle="collapse" href="#panel-element-82728">
                Collapsible Group Item #1
            </a>
        </div>
        <div class="panel-collapse collapse" id="panel-element-82728">
            <div class="panel-body">
                Anim pariatur cliche...
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <a class="panel-title collapsed" data-parent="#panel-677207" data-toggle="collapse" href="#panel-element-967782">
                Collapsible Group Item #2
            </a>
        </div>
        <div class="panel-collapse collapse" id="panel-element-967782">
            <div class="panel-body">
                Anim pariatur cliche...
            </div>
        </div>
    </div>
</div>
<!-- This is form -->
{% for entry in entries %}
<div class="panel panel-default">
    <div class="panel-heading">
        <a class="panel-title collapsed" data-parent="#panel-677207" data-toggle="collapse" href="#panel-element-{{entry.id}}">
            <h3>
                {{entry.name}}
                <small>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                        edit entry
                    </a>
                </small>
            </h3>
        </a>
    </div>
    <div class="panel-collapse collapse" id="panel-element-{{entry.id}}">
        <div class="panel-body">
            {{ entry.text |safe }}
        </div>
    </div>
</div>
{% endfor %}

{% endblock content %}