learning_log/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^learning_log/',include('learning_logs.urls',namespace='learning_logs')), 
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^reading/',include('reading.urls',namespace='reading')),
    url(r'^test/',include('mytest.urls',namespace='test')),
    url(r'^love/',include('lovestory.urls',namespace='love')),
    
]

learning_logs/urls.py
from django.conf.urls import url

from . import views

urlpatterns=[

	url(r'^$',views.index,name='index'),
	url(r'^topics/$',views.topics,name='topics'),
	url(r'^topic/(?P<topic_id>\d+)/$',views.topic,name='topic'),
	url(r'^new_topic/$',views.new_topic,name='new_topic'),
	url(r'^new_entry/(?P<topic_id>\d+)/$',views.new_entry,name='new_entry'),
	url(r'^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry,name='edit_entry'),

	url(r'^search/$',views.search,name='search'),

]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns=[
	url(r'^login/$',login,{'template_name':'users/login.html'},name='login'),
	url(r'^logout/$',views.logout_view,name='logout'),
	url(r'^register/$',views.register,name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
	"""用户学习的主题"""
	owner=models.ForeignKey(User)
	text=models.CharField(max_length=200)
	date_added=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		"""返回模型的字符串表示"""
		return self.text

class Entry(models.Model):
	"""条目：学到关于某个主题的具体知识"""
	topic=models.ForeignKey(Topic)
	name=models.CharField(max_length=200,default="None")
	text=models.TextField()
	date_added=models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural='entries'

	def __str__(self):
		return self.text[0:50]+"..."

learning_logs/forms.py
from django import forms

from .models import Topic,Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model=Topic
		fields=['text']
		labels={'text':''}

class EntryForm(forms.ModelForm):
	class Meta:
		model=Entry
		fields=['name','text']
		labels={'text':'','name':''}
		widgets={'text':forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .models import Topic,Entry
from .forms import TopicForm,EntryForm

from markdown import markdown

def index(request):
	"""学习笔记的主页"""
	return render(request,'learning_logs/index.html')

@login_required
def topics(request):
	"""显示所有的主题"""
	topics=Topic.objects.filter(owner=request.user).order_by('date_added')
	context={'topics':topics}
	return render(request,'learning_logs/topics.html',context)

@login_required
def topic(request,topic_id):
	"""显示单个主题和具体的条目信息"""
	topic=Topic.objects.get(id=topic_id)
	if topic.owner!=request.user:
		raise Http404

	entries=topic.entry_set.order_by('-date_added')
	for entry in entries:
		entry.text=markdown(entry.text,extensions=['markdown.extensions.extra',
													'markdown.extensions.codehilite',
													'markdown.extensions.toc',])


	context={'topic':topic,'entries':entries}
	return render(request,'learning_logs/topic.html',context)

@login_required
def new_topic(request):
	if request.method!='POST':
		form=TopicForm()
	else:
		form=TopicForm(request.POST)
		if form.is_valid():
			new_topic=form.save(commit=False)
			new_topic.owner=request.user
			new_topic.save()
			return HttpResponseRedirect(reverse('learning_logs:topics'))
	context={'form':form}
	return render(request,'learning_logs/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
	topic=Topic.objects.get(id=topic_id)
	if request.method!='POST':
		form=EntryForm()
	else:
		form=EntryForm(data=request.POST)
		if form.is_valid():
			new_entry=form.save(commit=False)
			new_entry.topic=topic
			new_entry.save()
			return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))
	context={'topic':topic,'form':form}
	return render(request,'learning_logs/new_entry.html',context)

@login_required
def edit_entry(request,entry_id):
	entry=Entry.objects.get(id=entry_id)
	topic=entry.topic
	if request.user!=topic.owner:
		raise Http404
	if request.method!='POST':
		form=EntryForm(instance=entry)
	else:
		form=EntryForm(instance=entry,data=request.POST)
		if form.is_valid:
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))
	context={'entry':entry,'topic':topic,'form':form}
	return render(request,'learning_logs/edit_entry.html',context)

@login_required
def search(request):
	if request.method=='POST':
		form_data=request.POST['search']

		search_result=Entry.objects.filter(Q(text__icontains=form_data) | Q(name__icontains=form_data)).order_by('-date_added')
		# search_result2=Entry.objects.filter(name__icontains=form_data).order_by('-date_added')
		# search_result=search_result1+search_result2
		entries=search_result
		for entry in entries:
			entry.text=markdown(entry.text,extensions=['markdown.extensions.extra',
													'markdown.extensions.codehilite',
													'markdown.extensions.toc',])

	# else:
	# 	from_data='No form data'
	# if request.user.username=="Zongqiqi":
	# 	msg="I am the king."
	# else:
	# 	msg=dir(request.user)
	context={'entries':entries}	
	return render(request,'learning_logs/search.html',context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link type="text/css" rel="stylesheet" href="{% static 'learning_logs/code.css' %}"/>
    <meta charset="utf-8">
    <meta content="IE=ege" http-equiv="X-UA-Compatible">
    <meta content="width=device-width,initial-sacle=1" name="viewport">
        <title>
        Learning Log
        </title>
            {% bootstrap_css %}
			{% bootstrap_javascript %}
    </meta>
    </meta>
    </meta>
    <link href="http://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"><!-- 搜索框 -->
    <link rel="stylesheet" type="text/css" href="{% static 'learning_logs/search.css' %}">

    </head>


    <body>
        <!-- Static navbar -->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button aria-controls="navbar" aria-expanded="false" class="navbar-toggle collapsed" data-target="#navbar" data-toggle="collapse" type="button">
                    </button>
                    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                        Learning Log
                    </a>
                </div>
                <div class="navbar-collapse collapse" id="navbar">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{% url 'learning_logs:topics' %}">
                                Topics
                            </a>
                        </li>
                        <li class="search bar7">
                              <form action="/learning_log/search/" method="post">
                                {% csrf_token %}
                                <input name='search' type="text" placeholder="请输入您要搜索的内容...">
                                <button class="search" type="submit"></button>
                              </form>

                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li>
                            <a>
                                Hello, {{ user.username }}.
                            </a>
                            <li ><a id="countDown"></a></li>
                        </li>
                        <li>
                            <a href="{% url 'users:logout' %}">
                                log out
                            </a>
                        </li>
                        {% else %}
                        <li>
                            <a href="{% url 'users:register' %}">
                                register
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'users:login' %}">
                                log in
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container">
            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </div>
        <!-- /container -->
    </body>
</html>







<!-- 倒计时代码 -->
<script type="text/javascript">
function countDown(years,months,days,hours,minutes){
  var dateFinal = new Date(years,months,days,hours,minutes);  //设置倒计时到达时间
  var dateNow = new Date();  //获取系统当前时间
  var dateSub = dateFinal - dateNow;  //计算差值，单位毫秒
  var day = hour = minute = second = dayBase = hourBase = minuteBase = secondBase = 0;  //初始化各个数值
  var timeHtml = '92710K:';
  timeHtml += '';
  dayBase = 24 * 60 * 60 * 1000;  //计算天数的基数，单位毫秒。1天等于24*60*60*1000毫秒
  hourBase = 60 * 60 * 1000;  //计算小时的基数，单位毫秒。1小时等于60*60*1000毫秒
  minuteBase = 60 * 1000;  //计算分钟的基数，单位毫秒。1分钟等于60*1000毫秒
  secondBase = 1000;  //计算秒钟的基数，单位毫秒。1秒钟等于1000毫秒
  day = Math.floor(dateSub / dayBase);  //计算天数，并取下限值。如 5.9天 = 5天
  hour = Math.floor(dateSub % dayBase / hourBase);  //计算小时，并取下限值。如 20.59小时 = 20小时
  minute = Math.floor(dateSub % dayBase % hourBase / minuteBase);  //计算分钟，并取下限值。如 20.59分钟 = 20分钟
  second = Math.floor(dateSub % dayBase % hourBase % minuteBase / secondBase);  //计算秒钟，并取下限值。如 20.59秒 = 20秒
  //当天数小于等于0时，就不用显示
  if(day <= 0){
    timeHtml += toDouble(hour) + '时' + toDouble(minute) + '分' + toDouble(second) + '秒';
  }else{
    timeHtml += day + '天' + toDouble(hour) + '时' + toDouble(minute) + '分' + toDouble(second) + '秒';
  }
  $('#countDown').html(timeHtml);
}
//当小时，分钟和秒钟小于 10 的时候会显示为个位数，比较难看，需要在前面加 0。
function toDouble(num){
  if(num < 10){
    return '0'+ num;
  }else{
    return '' + num;
  }
}
$(function(){
  setInterval(function(){
    countDown(2018,8,27,0,0);
  },1000);
});
</script>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block content %}

<h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>

<p>Edit entry:</p>

<form action=" {% url 'learning_logs:edit_entry' entry.id %} " method="post">
    {% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
    <button class="btn btn-primary" name="submit">
        save changes
    </button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% load staticfiles %}
{% block header %}
<div class="jumbotron">
    <h1>
        Track your learning.
    </h1>
</div>
{% endblock header %}
{% block content %}
<h2>
    <a href="{% url 'users:register' %}">
        Register an account
    </a>
    to make
your own Learning Log, and list the topics you're learning about.
</h2>
<h2>
    Whenever you learn something new about a topic, make an entry
summarizing what you've learned.
</h2>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}
{% block content %}

<h2><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></h2>
<p>Add new entry:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
	<button class="btn btn-primary" name="submit">Add entry</button>
	{% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h2>
    Add a new topic:
</h2>
{% endblock header %}

{% block content %}
<form action="{% url 'learning_logs:new_topic' %}" class="form" method="post">
    {% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
    <button class="btn btn-primary" name="submit">
        add topic
    </button>
    {% endbuttons %}
</form>
{% endblock content %}

learning_logs/templates/learning_logs/search.html
{% extends 'learning_logs/base.html' %}

{% block header %}
<h2>
    Search Result
</h2>
{% endblock header %}

{% block content %}

<div class="panel-group" id="panel-677207">
{% for entry in entries %}

<div class="panel panel-default">
    <div class="panel-heading">
        <a class="panel-title collapsed" data-parent="#panel-677207" data-toggle="collapse" href="#panel-element-{{entry.id}}">
            <h3>
                {{entry.name}}&nbsp;&nbsp;
                <small>
                    {{ entry.date_added|date:'M d, Y H:i' }}&nbsp;&nbsp;
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                        edit entry
                    </a>
                </small>
            </h3>
        </a>
    </div>
    <div class="panel-collapse collapse" id="panel-element-{{entry.id}}">
        <div class="panel-body">
            {{ entry.text |safe }}
        </div>
    </div>
</div>

<!-- panel -->
{% empty %}
Sorry there is no data what you need .
{% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
<h2>
    {{ topic }}
</h2>
{% endblock header %}

{% block content %}
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">
        add new entry
    </a>
</p>
<div class="panel-group" id="panel-677207">
{% for entry in entries %}

<div class="panel panel-default">
    <div class="panel-heading">
        <a class="panel-title collapsed" data-parent="#panel-677207" data-toggle="collapse" href="#panel-element-{{entry.id}}">
            <h3>
                {{entry.name}}&nbsp;&nbsp;
                <small>
                    {{ entry.date_added|date:'M d, Y H:i' }}&nbsp;&nbsp;
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                        edit entry
                    </a>
                </small>
            </h3>
        </a>
    </div>
    <div class="panel-collapse collapse" id="panel-element-{{entry.id}}">
        <div class="panel-body">
            {{ entry.text |safe }}
        </div>
    </div>
</div>

<!-- panel -->
{% empty %}
There are no entries for this topic yet.
{% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
<h1>
    Topics
</h1>
{% endblock header %}

{% block content %}
<ul>
    {% for topic in topics %}
    <li>
        <h3>
            <a href="{% url 'learning_logs:topic' topic.id %}">
                {{ topic }}
            </a>
        </h3>
    </li>
    {% empty %}
    <li>
        No topics have been added yet.
    </li>
    {% endfor %}
</ul>
<h3>
    <a href="{% url 'learning_logs:new_topic' %}">
        Add new topic
    </a>
</h3>
{% endblock content %}